/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb;


import io.rudin.minetest.tileserver.blockdb.tables.Blocks;
import io.rudin.minetest.tileserver.blockdb.tables.Chat;
import io.rudin.minetest.tileserver.blockdb.tables.FlywaySchemaHistory;
import io.rudin.minetest.tileserver.blockdb.tables.Missions;
import io.rudin.minetest.tileserver.blockdb.tables.Player;
import io.rudin.minetest.tileserver.blockdb.tables.PlayerInventories;
import io.rudin.minetest.tileserver.blockdb.tables.PlayerInventoryItems;
import io.rudin.minetest.tileserver.blockdb.tables.PlayerMetadata;
import io.rudin.minetest.tileserver.blockdb.tables.Poi;
import io.rudin.minetest.tileserver.blockdb.tables.Protector;
import io.rudin.minetest.tileserver.blockdb.tables.Shop;
import io.rudin.minetest.tileserver.blockdb.tables.Trainline;
import io.rudin.minetest.tileserver.blockdb.tables.Travelnet;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -426306518;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>blocks</code>.
     */
    public final Blocks BLOCKS = io.rudin.minetest.tileserver.blockdb.tables.Blocks.BLOCKS;

    /**
     * The table <code>chat</code>.
     */
    public final Chat CHAT = io.rudin.minetest.tileserver.blockdb.tables.Chat.CHAT;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = io.rudin.minetest.tileserver.blockdb.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>missions</code>.
     */
    public final Missions MISSIONS = io.rudin.minetest.tileserver.blockdb.tables.Missions.MISSIONS;

    /**
     * The table <code>player</code>.
     */
    public final Player PLAYER = io.rudin.minetest.tileserver.blockdb.tables.Player.PLAYER;

    /**
     * The table <code>player_inventories</code>.
     */
    public final PlayerInventories PLAYER_INVENTORIES = io.rudin.minetest.tileserver.blockdb.tables.PlayerInventories.PLAYER_INVENTORIES;

    /**
     * The table <code>player_inventory_items</code>.
     */
    public final PlayerInventoryItems PLAYER_INVENTORY_ITEMS = io.rudin.minetest.tileserver.blockdb.tables.PlayerInventoryItems.PLAYER_INVENTORY_ITEMS;

    /**
     * The table <code>player_metadata</code>.
     */
    public final PlayerMetadata PLAYER_METADATA = io.rudin.minetest.tileserver.blockdb.tables.PlayerMetadata.PLAYER_METADATA;

    /**
     * The table <code>poi</code>.
     */
    public final Poi POI = io.rudin.minetest.tileserver.blockdb.tables.Poi.POI;

    /**
     * The table <code>protector</code>.
     */
    public final Protector PROTECTOR = io.rudin.minetest.tileserver.blockdb.tables.Protector.PROTECTOR;

    /**
     * The table <code>shop</code>.
     */
    public final Shop SHOP = io.rudin.minetest.tileserver.blockdb.tables.Shop.SHOP;

    /**
     * The table <code>trainline</code>.
     */
    public final Trainline TRAINLINE = io.rudin.minetest.tileserver.blockdb.tables.Trainline.TRAINLINE;

    /**
     * The table <code>travelnet</code>.
     */
    public final Travelnet TRAVELNET = io.rudin.minetest.tileserver.blockdb.tables.Travelnet.TRAVELNET;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.MISSIONS_ID_SEQ,
            Sequences.POI_ID_SEQ,
            Sequences.PROTECTOR_ID_SEQ,
            Sequences.SHOP_ID_SEQ,
            Sequences.TRAINLINE_ID_SEQ,
            Sequences.TRAVELNET_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Blocks.BLOCKS,
            Chat.CHAT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Missions.MISSIONS,
            Player.PLAYER,
            PlayerInventories.PLAYER_INVENTORIES,
            PlayerInventoryItems.PLAYER_INVENTORY_ITEMS,
            PlayerMetadata.PLAYER_METADATA,
            Poi.POI,
            Protector.PROTECTOR,
            Shop.SHOP,
            Trainline.TRAINLINE,
            Travelnet.TRAVELNET);
    }
}
