/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb;


import io.rudin.minetest.tileserver.blockdb.tables.Blocks;
import io.rudin.minetest.tileserver.blockdb.tables.Player;
import io.rudin.minetest.tileserver.blockdb.tables.TileserverBlockChanges;
import io.rudin.minetest.tileserver.blockdb.tables.TileserverBlockDepth;
import io.rudin.minetest.tileserver.blockdb.tables.TileserverTiles;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>blocks</code>.
     */
    public static final Blocks BLOCKS = io.rudin.minetest.tileserver.blockdb.tables.Blocks.BLOCKS;

    /**
     * The table <code>player</code>.
     */
    public static final Player PLAYER = io.rudin.minetest.tileserver.blockdb.tables.Player.PLAYER;

    /**
     * The table <code>tileserver_block_changes</code>.
     */
    public static final TileserverBlockChanges TILESERVER_BLOCK_CHANGES = io.rudin.minetest.tileserver.blockdb.tables.TileserverBlockChanges.TILESERVER_BLOCK_CHANGES;

    /**
     * The table <code>tileserver_block_depth</code>.
     */
    public static final TileserverBlockDepth TILESERVER_BLOCK_DEPTH = io.rudin.minetest.tileserver.blockdb.tables.TileserverBlockDepth.TILESERVER_BLOCK_DEPTH;

    /**
     * The table <code>tileserver_tiles</code>.
     */
    public static final TileserverTiles TILESERVER_TILES = io.rudin.minetest.tileserver.blockdb.tables.TileserverTiles.TILESERVER_TILES;
}
