/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.tiledb;


import io.rudin.minetest.tileserver.tiledb.tables.FlywaySchemaHistory;
import io.rudin.minetest.tileserver.tiledb.tables.Tiles;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index TILES_PKEY = Indexes0.TILES_PKEY;
    public static final Index TILES_TIME = Indexes0.TILES_TIME;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index TILES_PKEY = Internal.createIndex("tiles_pkey", Tiles.TILES, new OrderField[] { Tiles.TILES.X, Tiles.TILES.Y, Tiles.TILES.Z, Tiles.TILES.LAYERID }, true);
        public static Index TILES_TIME = Internal.createIndex("tiles_time", Tiles.TILES, new OrderField[] { Tiles.TILES.MTIME }, false);
    }
}
