/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Blocks implements Serializable {

    private static final long serialVersionUID = 1275221715;

    private Integer posx;
    private Integer posy;
    private Integer posz;
    private byte[]  data;

    public Blocks() {}

    public Blocks(Blocks value) {
        this.posx = value.posx;
        this.posy = value.posy;
        this.posz = value.posz;
        this.data = value.data;
    }

    public Blocks(
        Integer posx,
        Integer posy,
        Integer posz,
        byte[]  data
    ) {
        this.posx = posx;
        this.posy = posy;
        this.posz = posz;
        this.data = data;
    }

    public Integer getPosx() {
        return this.posx;
    }

    public void setPosx(Integer posx) {
        this.posx = posx;
    }

    public Integer getPosy() {
        return this.posy;
    }

    public void setPosy(Integer posy) {
        this.posy = posy;
    }

    public Integer getPosz() {
        return this.posz;
    }

    public void setPosz(Integer posz) {
        this.posz = posz;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte... data) {
        this.data = data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Blocks (");

        sb.append(posx);
        sb.append(", ").append(posy);
        sb.append(", ").append(posz);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
