/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chat implements Serializable {

    private static final long serialVersionUID = 1685142237;

    private Long   time;
    private String playername;
    private String text;

    public Chat() {}

    public Chat(Chat value) {
        this.time = value.time;
        this.playername = value.playername;
        this.text = value.text;
    }

    public Chat(
        Long   time,
        String playername,
        String text
    ) {
        this.time = time;
        this.playername = playername;
        this.text = text;
    }

    public Long getTime() {
        return this.time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getPlayername() {
        return this.playername;
    }

    public void setPlayername(String playername) {
        this.playername = playername;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chat (");

        sb.append(time);
        sb.append(", ").append(playername);
        sb.append(", ").append(text);

        sb.append(")");
        return sb.toString();
    }
}
