/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerMetadata implements Serializable {

    private static final long serialVersionUID = -1290842358;

    private String player;
    private String attr;
    private String value;

    public PlayerMetadata() {}

    public PlayerMetadata(PlayerMetadata value) {
        this.player = value.player;
        this.attr = value.attr;
        this.value = value.value;
    }

    public PlayerMetadata(
        String player,
        String attr,
        String value
    ) {
        this.player = player;
        this.attr = attr;
        this.value = value;
    }

    public String getPlayer() {
        return this.player;
    }

    public void setPlayer(String player) {
        this.player = player;
    }

    public String getAttr() {
        return this.attr;
    }

    public void setAttr(String attr) {
        this.attr = attr;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerMetadata (");

        sb.append(player);
        sb.append(", ").append(attr);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
