/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Player implements Serializable {

    private static final long serialVersionUID = 513749400;

    private String     name;
    private BigDecimal pitch;
    private BigDecimal yaw;
    private BigDecimal posx;
    private BigDecimal posy;
    private BigDecimal posz;
    private Integer    hp;
    private Integer    breath;
    private Timestamp  creationDate;
    private Timestamp  modificationDate;

    public Player() {}

    public Player(Player value) {
        this.name = value.name;
        this.pitch = value.pitch;
        this.yaw = value.yaw;
        this.posx = value.posx;
        this.posy = value.posy;
        this.posz = value.posz;
        this.hp = value.hp;
        this.breath = value.breath;
        this.creationDate = value.creationDate;
        this.modificationDate = value.modificationDate;
    }

    public Player(
        String     name,
        BigDecimal pitch,
        BigDecimal yaw,
        BigDecimal posx,
        BigDecimal posy,
        BigDecimal posz,
        Integer    hp,
        Integer    breath,
        Timestamp  creationDate,
        Timestamp  modificationDate
    ) {
        this.name = name;
        this.pitch = pitch;
        this.yaw = yaw;
        this.posx = posx;
        this.posy = posy;
        this.posz = posz;
        this.hp = hp;
        this.breath = breath;
        this.creationDate = creationDate;
        this.modificationDate = modificationDate;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPitch() {
        return this.pitch;
    }

    public void setPitch(BigDecimal pitch) {
        this.pitch = pitch;
    }

    public BigDecimal getYaw() {
        return this.yaw;
    }

    public void setYaw(BigDecimal yaw) {
        this.yaw = yaw;
    }

    public BigDecimal getPosx() {
        return this.posx;
    }

    public void setPosx(BigDecimal posx) {
        this.posx = posx;
    }

    public BigDecimal getPosy() {
        return this.posy;
    }

    public void setPosy(BigDecimal posy) {
        this.posy = posy;
    }

    public BigDecimal getPosz() {
        return this.posz;
    }

    public void setPosz(BigDecimal posz) {
        this.posz = posz;
    }

    public Integer getHp() {
        return this.hp;
    }

    public void setHp(Integer hp) {
        this.hp = hp;
    }

    public Integer getBreath() {
        return this.breath;
    }

    public void setBreath(Integer breath) {
        this.breath = breath;
    }

    public Timestamp getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Timestamp creationDate) {
        this.creationDate = creationDate;
    }

    public Timestamp getModificationDate() {
        return this.modificationDate;
    }

    public void setModificationDate(Timestamp modificationDate) {
        this.modificationDate = modificationDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Player (");

        sb.append(name);
        sb.append(", ").append(pitch);
        sb.append(", ").append(yaw);
        sb.append(", ").append(posx);
        sb.append(", ").append(posy);
        sb.append(", ").append(posz);
        sb.append(", ").append(hp);
        sb.append(", ").append(breath);
        sb.append(", ").append(creationDate);
        sb.append(", ").append(modificationDate);

        sb.append(")");
        return sb.toString();
    }
}
