/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerInventories implements Serializable {

    private static final long serialVersionUID = -200864205;

    private String  player;
    private Integer invId;
    private Integer invWidth;
    private String  invName;
    private Integer invSize;

    public PlayerInventories() {}

    public PlayerInventories(PlayerInventories value) {
        this.player = value.player;
        this.invId = value.invId;
        this.invWidth = value.invWidth;
        this.invName = value.invName;
        this.invSize = value.invSize;
    }

    public PlayerInventories(
        String  player,
        Integer invId,
        Integer invWidth,
        String  invName,
        Integer invSize
    ) {
        this.player = player;
        this.invId = invId;
        this.invWidth = invWidth;
        this.invName = invName;
        this.invSize = invSize;
    }

    public String getPlayer() {
        return this.player;
    }

    public void setPlayer(String player) {
        this.player = player;
    }

    public Integer getInvId() {
        return this.invId;
    }

    public void setInvId(Integer invId) {
        this.invId = invId;
    }

    public Integer getInvWidth() {
        return this.invWidth;
    }

    public void setInvWidth(Integer invWidth) {
        this.invWidth = invWidth;
    }

    public String getInvName() {
        return this.invName;
    }

    public void setInvName(String invName) {
        this.invName = invName;
    }

    public Integer getInvSize() {
        return this.invSize;
    }

    public void setInvSize(Integer invSize) {
        this.invSize = invSize;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerInventories (");

        sb.append(player);
        sb.append(", ").append(invId);
        sb.append(", ").append(invWidth);
        sb.append(", ").append(invName);
        sb.append(", ").append(invSize);

        sb.append(")");
        return sb.toString();
    }
}
