/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerInventoryItems implements Serializable {

    private static final long serialVersionUID = 1597557548;

    private String  player;
    private Integer invId;
    private Integer slotId;
    private String  item;

    public PlayerInventoryItems() {}

    public PlayerInventoryItems(PlayerInventoryItems value) {
        this.player = value.player;
        this.invId = value.invId;
        this.slotId = value.slotId;
        this.item = value.item;
    }

    public PlayerInventoryItems(
        String  player,
        Integer invId,
        Integer slotId,
        String  item
    ) {
        this.player = player;
        this.invId = invId;
        this.slotId = slotId;
        this.item = item;
    }

    public String getPlayer() {
        return this.player;
    }

    public void setPlayer(String player) {
        this.player = player;
    }

    public Integer getInvId() {
        return this.invId;
    }

    public void setInvId(Integer invId) {
        this.invId = invId;
    }

    public Integer getSlotId() {
        return this.slotId;
    }

    public void setSlotId(Integer slotId) {
        this.slotId = slotId;
    }

    public String getItem() {
        return this.item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlayerInventoryItems (");

        sb.append(player);
        sb.append(", ").append(invId);
        sb.append(", ").append(slotId);
        sb.append(", ").append(item);

        sb.append(")");
        return sb.toString();
    }
}
