/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shop implements Serializable {

    private static final long serialVersionUID = 1974012631;

    private Integer id;
    private String  type;
    private String  owner;
    private String  inItem;
    private Integer inCount;
    private String  outItem;
    private Integer outCount;
    private Integer outStock;
    private Boolean active;
    private Integer x;
    private Integer y;
    private Integer z;
    private Integer posx;
    private Integer posy;
    private Integer posz;
    private Long    mtime;

    public Shop() {}

    public Shop(Shop value) {
        this.id = value.id;
        this.type = value.type;
        this.owner = value.owner;
        this.inItem = value.inItem;
        this.inCount = value.inCount;
        this.outItem = value.outItem;
        this.outCount = value.outCount;
        this.outStock = value.outStock;
        this.active = value.active;
        this.x = value.x;
        this.y = value.y;
        this.z = value.z;
        this.posx = value.posx;
        this.posy = value.posy;
        this.posz = value.posz;
        this.mtime = value.mtime;
    }

    public Shop(
        Integer id,
        String  type,
        String  owner,
        String  inItem,
        Integer inCount,
        String  outItem,
        Integer outCount,
        Integer outStock,
        Boolean active,
        Integer x,
        Integer y,
        Integer z,
        Integer posx,
        Integer posy,
        Integer posz,
        Long    mtime
    ) {
        this.id = id;
        this.type = type;
        this.owner = owner;
        this.inItem = inItem;
        this.inCount = inCount;
        this.outItem = outItem;
        this.outCount = outCount;
        this.outStock = outStock;
        this.active = active;
        this.x = x;
        this.y = y;
        this.z = z;
        this.posx = posx;
        this.posy = posy;
        this.posz = posz;
        this.mtime = mtime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getInItem() {
        return this.inItem;
    }

    public void setInItem(String inItem) {
        this.inItem = inItem;
    }

    public Integer getInCount() {
        return this.inCount;
    }

    public void setInCount(Integer inCount) {
        this.inCount = inCount;
    }

    public String getOutItem() {
        return this.outItem;
    }

    public void setOutItem(String outItem) {
        this.outItem = outItem;
    }

    public Integer getOutCount() {
        return this.outCount;
    }

    public void setOutCount(Integer outCount) {
        this.outCount = outCount;
    }

    public Integer getOutStock() {
        return this.outStock;
    }

    public void setOutStock(Integer outStock) {
        this.outStock = outStock;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Integer getX() {
        return this.x;
    }

    public void setX(Integer x) {
        this.x = x;
    }

    public Integer getY() {
        return this.y;
    }

    public void setY(Integer y) {
        this.y = y;
    }

    public Integer getZ() {
        return this.z;
    }

    public void setZ(Integer z) {
        this.z = z;
    }

    public Integer getPosx() {
        return this.posx;
    }

    public void setPosx(Integer posx) {
        this.posx = posx;
    }

    public Integer getPosy() {
        return this.posy;
    }

    public void setPosy(Integer posy) {
        this.posy = posy;
    }

    public Integer getPosz() {
        return this.posz;
    }

    public void setPosz(Integer posz) {
        this.posz = posz;
    }

    public Long getMtime() {
        return this.mtime;
    }

    public void setMtime(Long mtime) {
        this.mtime = mtime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Shop (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(owner);
        sb.append(", ").append(inItem);
        sb.append(", ").append(inCount);
        sb.append(", ").append(outItem);
        sb.append(", ").append(outCount);
        sb.append(", ").append(outStock);
        sb.append(", ").append(active);
        sb.append(", ").append(x);
        sb.append(", ").append(y);
        sb.append(", ").append(z);
        sb.append(", ").append(posx);
        sb.append(", ").append(posy);
        sb.append(", ").append(posz);
        sb.append(", ").append(mtime);

        sb.append(")");
        return sb.toString();
    }
}
