/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TileserverBlockChanges implements Serializable {

    private static final long serialVersionUID = -255927634;

    private Integer posx;
    private Integer posy;
    private Integer posz;
    private Boolean changed;

    public TileserverBlockChanges() {}

    public TileserverBlockChanges(TileserverBlockChanges value) {
        this.posx = value.posx;
        this.posy = value.posy;
        this.posz = value.posz;
        this.changed = value.changed;
    }

    public TileserverBlockChanges(
        Integer posx,
        Integer posy,
        Integer posz,
        Boolean changed
    ) {
        this.posx = posx;
        this.posy = posy;
        this.posz = posz;
        this.changed = changed;
    }

    public Integer getPosx() {
        return this.posx;
    }

    public void setPosx(Integer posx) {
        this.posx = posx;
    }

    public Integer getPosy() {
        return this.posy;
    }

    public void setPosy(Integer posy) {
        this.posy = posy;
    }

    public Integer getPosz() {
        return this.posz;
    }

    public void setPosz(Integer posz) {
        this.posz = posz;
    }

    public Boolean getChanged() {
        return this.changed;
    }

    public void setChanged(Boolean changed) {
        this.changed = changed;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TileserverBlockChanges (");

        sb.append(posx);
        sb.append(", ").append(posy);
        sb.append(", ").append(posz);
        sb.append(", ").append(changed);

        sb.append(")");
        return sb.toString();
    }
}
