/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables;


import io.rudin.minetest.tileserver.blockdb.DefaultSchema;
import io.rudin.minetest.tileserver.blockdb.Indexes;
import io.rudin.minetest.tileserver.blockdb.Keys;
import io.rudin.minetest.tileserver.blockdb.tables.records.PoiRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Poi extends TableImpl<PoiRecord> {

    private static final long serialVersionUID = -1911319382;

    /**
     * The reference instance of <code>poi</code>
     */
    public static final Poi POI = new Poi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PoiRecord> getRecordType() {
        return PoiRecord.class;
    }

    /**
     * The column <code>poi.id</code>.
     */
    public final TableField<PoiRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('poi_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>poi.name</code>.
     */
    public final TableField<PoiRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>poi.category</code>.
     */
    public final TableField<PoiRecord, String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>poi.owner</code>.
     */
    public final TableField<PoiRecord, String> OWNER = createField("owner", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>poi.active</code>.
     */
    public final TableField<PoiRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>poi.x</code>.
     */
    public final TableField<PoiRecord, Integer> X = createField("x", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>poi.y</code>.
     */
    public final TableField<PoiRecord, Integer> Y = createField("y", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>poi.z</code>.
     */
    public final TableField<PoiRecord, Integer> Z = createField("z", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>poi.posx</code>.
     */
    public final TableField<PoiRecord, Integer> POSX = createField("posx", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>poi.posy</code>.
     */
    public final TableField<PoiRecord, Integer> POSY = createField("posy", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>poi.posz</code>.
     */
    public final TableField<PoiRecord, Integer> POSZ = createField("posz", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>poi.mtime</code>.
     */
    public final TableField<PoiRecord, Long> MTIME = createField("mtime", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>poi</code> table reference
     */
    public Poi() {
        this(DSL.name("poi"), null);
    }

    /**
     * Create an aliased <code>poi</code> table reference
     */
    public Poi(String alias) {
        this(DSL.name(alias), POI);
    }

    /**
     * Create an aliased <code>poi</code> table reference
     */
    public Poi(Name alias) {
        this(alias, POI);
    }

    private Poi(Name alias, Table<PoiRecord> aliased) {
        this(alias, aliased, null);
    }

    private Poi(Name alias, Table<PoiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.POI_MAPBLOCK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PoiRecord, Integer> getIdentity() {
        return Keys.IDENTITY_POI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Poi as(String alias) {
        return new Poi(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Poi as(Name alias) {
        return new Poi(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Poi rename(String name) {
        return new Poi(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Poi rename(Name name) {
        return new Poi(name, null);
    }
}
