/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables;


import io.rudin.minetest.tileserver.blockdb.DefaultSchema;
import io.rudin.minetest.tileserver.blockdb.Indexes;
import io.rudin.minetest.tileserver.blockdb.Keys;
import io.rudin.minetest.tileserver.blockdb.tables.records.TrainlineRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trainline extends TableImpl<TrainlineRecord> {

    private static final long serialVersionUID = -213973607;

    /**
     * The reference instance of <code>trainline</code>
     */
    public static final Trainline TRAINLINE = new Trainline();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrainlineRecord> getRecordType() {
        return TrainlineRecord.class;
    }

    /**
     * The column <code>trainline.id</code>.
     */
    public final TableField<TrainlineRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('trainline_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>trainline.station</code>.
     */
    public final TableField<TrainlineRecord, String> STATION = createField("station", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>trainline.line</code>.
     */
    public final TableField<TrainlineRecord, String> LINE = createField("line", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>trainline.index</code>.
     */
    public final TableField<TrainlineRecord, Integer> INDEX = createField("index", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>trainline.owner</code>.
     */
    public final TableField<TrainlineRecord, String> OWNER = createField("owner", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>trainline.x</code>.
     */
    public final TableField<TrainlineRecord, Integer> X = createField("x", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>trainline.y</code>.
     */
    public final TableField<TrainlineRecord, Integer> Y = createField("y", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>trainline.z</code>.
     */
    public final TableField<TrainlineRecord, Integer> Z = createField("z", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>trainline.posx</code>.
     */
    public final TableField<TrainlineRecord, Integer> POSX = createField("posx", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>trainline.posy</code>.
     */
    public final TableField<TrainlineRecord, Integer> POSY = createField("posy", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>trainline.posz</code>.
     */
    public final TableField<TrainlineRecord, Integer> POSZ = createField("posz", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>trainline.mtime</code>.
     */
    public final TableField<TrainlineRecord, Long> MTIME = createField("mtime", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>trainline</code> table reference
     */
    public Trainline() {
        this(DSL.name("trainline"), null);
    }

    /**
     * Create an aliased <code>trainline</code> table reference
     */
    public Trainline(String alias) {
        this(DSL.name(alias), TRAINLINE);
    }

    /**
     * Create an aliased <code>trainline</code> table reference
     */
    public Trainline(Name alias) {
        this(alias, TRAINLINE);
    }

    private Trainline(Name alias, Table<TrainlineRecord> aliased) {
        this(alias, aliased, null);
    }

    private Trainline(Name alias, Table<TrainlineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TRAINLINE_MAPBLOCK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TrainlineRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TRAINLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Trainline as(String alias) {
        return new Trainline(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Trainline as(Name alias) {
        return new Trainline(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Trainline rename(String name) {
        return new Trainline(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Trainline rename(Name name) {
        return new Trainline(name, null);
    }
}
