/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables;


import io.rudin.minetest.tileserver.blockdb.DefaultSchema;
import io.rudin.minetest.tileserver.blockdb.Indexes;
import io.rudin.minetest.tileserver.blockdb.Keys;
import io.rudin.minetest.tileserver.blockdb.tables.records.TravelnetRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Travelnet extends TableImpl<TravelnetRecord> {

    private static final long serialVersionUID = -2048197933;

    /**
     * The reference instance of <code>travelnet</code>
     */
    public static final Travelnet TRAVELNET = new Travelnet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TravelnetRecord> getRecordType() {
        return TravelnetRecord.class;
    }

    /**
     * The column <code>travelnet.id</code>.
     */
    public final TableField<TravelnetRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('travelnet_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>travelnet.name</code>.
     */
    public final TableField<TravelnetRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>travelnet.network</code>.
     */
    public final TableField<TravelnetRecord, String> NETWORK = createField("network", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>travelnet.owner</code>.
     */
    public final TableField<TravelnetRecord, String> OWNER = createField("owner", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>travelnet.x</code>.
     */
    public final TableField<TravelnetRecord, Integer> X = createField("x", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>travelnet.y</code>.
     */
    public final TableField<TravelnetRecord, Integer> Y = createField("y", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>travelnet.z</code>.
     */
    public final TableField<TravelnetRecord, Integer> Z = createField("z", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>travelnet.posx</code>.
     */
    public final TableField<TravelnetRecord, Integer> POSX = createField("posx", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>travelnet.posy</code>.
     */
    public final TableField<TravelnetRecord, Integer> POSY = createField("posy", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>travelnet.posz</code>.
     */
    public final TableField<TravelnetRecord, Integer> POSZ = createField("posz", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>travelnet.mtime</code>.
     */
    public final TableField<TravelnetRecord, Long> MTIME = createField("mtime", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>travelnet</code> table reference
     */
    public Travelnet() {
        this(DSL.name("travelnet"), null);
    }

    /**
     * Create an aliased <code>travelnet</code> table reference
     */
    public Travelnet(String alias) {
        this(DSL.name(alias), TRAVELNET);
    }

    /**
     * Create an aliased <code>travelnet</code> table reference
     */
    public Travelnet(Name alias) {
        this(alias, TRAVELNET);
    }

    private Travelnet(Name alias, Table<TravelnetRecord> aliased) {
        this(alias, aliased, null);
    }

    private Travelnet(Name alias, Table<TravelnetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TRAVELNET_MAPBLOCK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TravelnetRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TRAVELNET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Travelnet as(String alias) {
        return new Travelnet(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Travelnet as(Name alias) {
        return new Travelnet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Travelnet rename(String name) {
        return new Travelnet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Travelnet rename(Name name) {
        return new Travelnet(name, null);
    }
}
