/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.daos;


import io.rudin.minetest.tileserver.blockdb.tables.Blocks;
import io.rudin.minetest.tileserver.blockdb.tables.records.BlocksRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record3;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlocksDao extends DAOImpl<BlocksRecord, io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks, Record3<Integer, Integer, Integer>> {

    /**
     * Create a new BlocksDao without any configuration
     */
    public BlocksDao() {
        super(Blocks.BLOCKS, io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks.class);
    }

    /**
     * Create a new BlocksDao with an attached configuration
     */
    public BlocksDao(Configuration configuration) {
        super(Blocks.BLOCKS, io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record3<Integer, Integer, Integer> getId(io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks object) {
        return compositeKeyRecord(object.getPosx(), object.getPosy(), object.getPosz());
    }

    /**
     * Fetch records that have <code>posx IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks> fetchByPosx(Integer... values) {
        return fetch(Blocks.BLOCKS.POSX, values);
    }

    /**
     * Fetch records that have <code>posy IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks> fetchByPosy(Integer... values) {
        return fetch(Blocks.BLOCKS.POSY, values);
    }

    /**
     * Fetch records that have <code>posz IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks> fetchByPosz(Integer... values) {
        return fetch(Blocks.BLOCKS.POSZ, values);
    }

    /**
     * Fetch records that have <code>data IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks> fetchByData(byte[]... values) {
        return fetch(Blocks.BLOCKS.DATA, values);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Blocks> fetchByMtime(Long... values) {
        return fetch(Blocks.BLOCKS.MTIME, values);
    }
}
