/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.daos;


import io.rudin.minetest.tileserver.blockdb.tables.PlayerInventoryItems;
import io.rudin.minetest.tileserver.blockdb.tables.records.PlayerInventoryItemsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record3;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerInventoryItemsDao extends DAOImpl<PlayerInventoryItemsRecord, io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems, Record3<String, Integer, Integer>> {

    /**
     * Create a new PlayerInventoryItemsDao without any configuration
     */
    public PlayerInventoryItemsDao() {
        super(PlayerInventoryItems.PLAYER_INVENTORY_ITEMS, io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems.class);
    }

    /**
     * Create a new PlayerInventoryItemsDao with an attached configuration
     */
    public PlayerInventoryItemsDao(Configuration configuration) {
        super(PlayerInventoryItems.PLAYER_INVENTORY_ITEMS, io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record3<String, Integer, Integer> getId(io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems object) {
        return compositeKeyRecord(object.getPlayer(), object.getInvId(), object.getSlotId());
    }

    /**
     * Fetch records that have <code>player IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems> fetchByPlayer(String... values) {
        return fetch(PlayerInventoryItems.PLAYER_INVENTORY_ITEMS.PLAYER, values);
    }

    /**
     * Fetch records that have <code>inv_id IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems> fetchByInvId(Integer... values) {
        return fetch(PlayerInventoryItems.PLAYER_INVENTORY_ITEMS.INV_ID, values);
    }

    /**
     * Fetch records that have <code>slot_id IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems> fetchBySlotId(Integer... values) {
        return fetch(PlayerInventoryItems.PLAYER_INVENTORY_ITEMS.SLOT_ID, values);
    }

    /**
     * Fetch records that have <code>item IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventoryItems> fetchByItem(String... values) {
        return fetch(PlayerInventoryItems.PLAYER_INVENTORY_ITEMS.ITEM, values);
    }
}
