/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.daos;


import io.rudin.minetest.tileserver.blockdb.tables.Player;
import io.rudin.minetest.tileserver.blockdb.tables.records.PlayerRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerDao extends DAOImpl<PlayerRecord, io.rudin.minetest.tileserver.blockdb.tables.pojos.Player, String> {

    /**
     * Create a new PlayerDao without any configuration
     */
    public PlayerDao() {
        super(Player.PLAYER, io.rudin.minetest.tileserver.blockdb.tables.pojos.Player.class);
    }

    /**
     * Create a new PlayerDao with an attached configuration
     */
    public PlayerDao(Configuration configuration) {
        super(Player.PLAYER, io.rudin.minetest.tileserver.blockdb.tables.pojos.Player.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(io.rudin.minetest.tileserver.blockdb.tables.pojos.Player object) {
        return object.getName();
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByName(String... values) {
        return fetch(Player.PLAYER.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>name = value</code>
     */
    public io.rudin.minetest.tileserver.blockdb.tables.pojos.Player fetchOneByName(String value) {
        return fetchOne(Player.PLAYER.NAME, value);
    }

    /**
     * Fetch records that have <code>pitch IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByPitch(BigDecimal... values) {
        return fetch(Player.PLAYER.PITCH, values);
    }

    /**
     * Fetch records that have <code>yaw IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByYaw(BigDecimal... values) {
        return fetch(Player.PLAYER.YAW, values);
    }

    /**
     * Fetch records that have <code>posx IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByPosx(BigDecimal... values) {
        return fetch(Player.PLAYER.POSX, values);
    }

    /**
     * Fetch records that have <code>posy IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByPosy(BigDecimal... values) {
        return fetch(Player.PLAYER.POSY, values);
    }

    /**
     * Fetch records that have <code>posz IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByPosz(BigDecimal... values) {
        return fetch(Player.PLAYER.POSZ, values);
    }

    /**
     * Fetch records that have <code>hp IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByHp(Integer... values) {
        return fetch(Player.PLAYER.HP, values);
    }

    /**
     * Fetch records that have <code>breath IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByBreath(Integer... values) {
        return fetch(Player.PLAYER.BREATH, values);
    }

    /**
     * Fetch records that have <code>creation_date IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByCreationDate(Timestamp... values) {
        return fetch(Player.PLAYER.CREATION_DATE, values);
    }

    /**
     * Fetch records that have <code>modification_date IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.Player> fetchByModificationDate(Timestamp... values) {
        return fetch(Player.PLAYER.MODIFICATION_DATE, values);
    }
}
