/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.daos;


import io.rudin.minetest.tileserver.blockdb.tables.PlayerInventories;
import io.rudin.minetest.tileserver.blockdb.tables.records.PlayerInventoriesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerInventoriesDao extends DAOImpl<PlayerInventoriesRecord, io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories, Record2<String, Integer>> {

    /**
     * Create a new PlayerInventoriesDao without any configuration
     */
    public PlayerInventoriesDao() {
        super(PlayerInventories.PLAYER_INVENTORIES, io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories.class);
    }

    /**
     * Create a new PlayerInventoriesDao with an attached configuration
     */
    public PlayerInventoriesDao(Configuration configuration) {
        super(PlayerInventories.PLAYER_INVENTORIES, io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, Integer> getId(io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories object) {
        return compositeKeyRecord(object.getPlayer(), object.getInvId());
    }

    /**
     * Fetch records that have <code>player IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories> fetchByPlayer(String... values) {
        return fetch(PlayerInventories.PLAYER_INVENTORIES.PLAYER, values);
    }

    /**
     * Fetch records that have <code>inv_id IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories> fetchByInvId(Integer... values) {
        return fetch(PlayerInventories.PLAYER_INVENTORIES.INV_ID, values);
    }

    /**
     * Fetch records that have <code>inv_width IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories> fetchByInvWidth(Integer... values) {
        return fetch(PlayerInventories.PLAYER_INVENTORIES.INV_WIDTH, values);
    }

    /**
     * Fetch records that have <code>inv_name IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories> fetchByInvName(String... values) {
        return fetch(PlayerInventories.PLAYER_INVENTORIES.INV_NAME, values);
    }

    /**
     * Fetch records that have <code>inv_size IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.PlayerInventories> fetchByInvSize(Integer... values) {
        return fetch(PlayerInventories.PLAYER_INVENTORIES.INV_SIZE, values);
    }
}
