/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.daos;


import io.rudin.minetest.tileserver.blockdb.tables.TileserverBlockDepth;
import io.rudin.minetest.tileserver.blockdb.tables.records.TileserverBlockDepthRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TileserverBlockDepthDao extends DAOImpl<TileserverBlockDepthRecord, io.rudin.minetest.tileserver.blockdb.tables.pojos.TileserverBlockDepth, Record2<Integer, Integer>> {

    /**
     * Create a new TileserverBlockDepthDao without any configuration
     */
    public TileserverBlockDepthDao() {
        super(TileserverBlockDepth.TILESERVER_BLOCK_DEPTH, io.rudin.minetest.tileserver.blockdb.tables.pojos.TileserverBlockDepth.class);
    }

    /**
     * Create a new TileserverBlockDepthDao with an attached configuration
     */
    public TileserverBlockDepthDao(Configuration configuration) {
        super(TileserverBlockDepth.TILESERVER_BLOCK_DEPTH, io.rudin.minetest.tileserver.blockdb.tables.pojos.TileserverBlockDepth.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(io.rudin.minetest.tileserver.blockdb.tables.pojos.TileserverBlockDepth object) {
        return compositeKeyRecord(object.getPosx(), object.getPosz());
    }

    /**
     * Fetch records that have <code>posx IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.TileserverBlockDepth> fetchByPosx(Integer... values) {
        return fetch(TileserverBlockDepth.TILESERVER_BLOCK_DEPTH.POSX, values);
    }

    /**
     * Fetch records that have <code>posz IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.TileserverBlockDepth> fetchByPosz(Integer... values) {
        return fetch(TileserverBlockDepth.TILESERVER_BLOCK_DEPTH.POSZ, values);
    }

    /**
     * Fetch records that have <code>visibley IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.blockdb.tables.pojos.TileserverBlockDepth> fetchByVisibley(Integer... values) {
        return fetch(TileserverBlockDepth.TILESERVER_BLOCK_DEPTH.VISIBLEY, values);
    }
}
