/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.tiledb.tables.daos;


import io.rudin.minetest.tileserver.tiledb.tables.Tiles;
import io.rudin.minetest.tileserver.tiledb.tables.records.TilesRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record4;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TilesDao extends DAOImpl<TilesRecord, io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles, Record4<Integer, Integer, Integer, Integer>> {

    /**
     * Create a new TilesDao without any configuration
     */
    public TilesDao() {
        super(Tiles.TILES, io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles.class);
    }

    /**
     * Create a new TilesDao with an attached configuration
     */
    public TilesDao(Configuration configuration) {
        super(Tiles.TILES, io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record4<Integer, Integer, Integer, Integer> getId(io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles object) {
        return compositeKeyRecord(object.getX(), object.getY(), object.getZ(), object.getLayerid());
    }

    /**
     * Fetch records that have <code>x IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles> fetchByX(Integer... values) {
        return fetch(Tiles.TILES.X, values);
    }

    /**
     * Fetch records that have <code>y IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles> fetchByY(Integer... values) {
        return fetch(Tiles.TILES.Y, values);
    }

    /**
     * Fetch records that have <code>z IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles> fetchByZ(Integer... values) {
        return fetch(Tiles.TILES.Z, values);
    }

    /**
     * Fetch records that have <code>mtime IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles> fetchByMtime(Long... values) {
        return fetch(Tiles.TILES.MTIME, values);
    }

    /**
     * Fetch records that have <code>tile IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles> fetchByTile(byte[]... values) {
        return fetch(Tiles.TILES.TILE, values);
    }

    /**
     * Fetch records that have <code>layerid IN (values)</code>
     */
    public List<io.rudin.minetest.tileserver.tiledb.tables.pojos.Tiles> fetchByLayerid(Integer... values) {
        return fetch(Tiles.TILES.LAYERID, values);
    }
}
