/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.Chat;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRecord extends TableRecordImpl<ChatRecord> implements Record3<Long, String, String> {

    private static final long serialVersionUID = 731552506;

    /**
     * Setter for <code>chat.time</code>.
     */
    public void setTime(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>chat.time</code>.
     */
    public Long getTime() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>chat.playername</code>.
     */
    public void setPlayername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>chat.playername</code>.
     */
    public String getPlayername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>chat.text</code>.
     */
    public void setText(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>chat.text</code>.
     */
    public String getText() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Chat.CHAT.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Chat.CHAT.PLAYERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Chat.CHAT.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPlayername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPlayername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value1(Long value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value2(String value) {
        setPlayername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord value3(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChatRecord values(Long value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRecord
     */
    public ChatRecord() {
        super(Chat.CHAT);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    public ChatRecord(Long time, String playername, String text) {
        super(Chat.CHAT);

        set(0, time);
        set(1, playername);
        set(2, text);
    }
}
