/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.Missions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MissionsRecord extends TableRecordImpl<MissionsRecord> implements Record12<Integer, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> {

    private static final long serialVersionUID = -467495776;

    /**
     * Setter for <code>missions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>missions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>missions.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>missions.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>missions.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>missions.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>missions.time</code>.
     */
    public void setTime(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>missions.time</code>.
     */
    public Integer getTime() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>missions.owner</code>.
     */
    public void setOwner(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>missions.owner</code>.
     */
    public String getOwner() {
        return (String) get(4);
    }

    /**
     * Setter for <code>missions.x</code>.
     */
    public void setX(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>missions.x</code>.
     */
    public Integer getX() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>missions.y</code>.
     */
    public void setY(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>missions.y</code>.
     */
    public Integer getY() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>missions.z</code>.
     */
    public void setZ(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>missions.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>missions.posx</code>.
     */
    public void setPosx(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>missions.posx</code>.
     */
    public Integer getPosx() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>missions.posy</code>.
     */
    public void setPosy(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>missions.posy</code>.
     */
    public Integer getPosy() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>missions.posz</code>.
     */
    public void setPosz(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>missions.posz</code>.
     */
    public Integer getPosz() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>missions.mtime</code>.
     */
    public void setMtime(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>missions.mtime</code>.
     */
    public Long getMtime() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Missions.MISSIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Missions.MISSIONS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Missions.MISSIONS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Missions.MISSIONS.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Missions.MISSIONS.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Missions.MISSIONS.X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Missions.MISSIONS.Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Missions.MISSIONS.Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Missions.MISSIONS.POSX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Missions.MISSIONS.POSY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Missions.MISSIONS.POSZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Missions.MISSIONS.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value4(Integer value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value5(String value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value6(Integer value) {
        setX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value7(Integer value) {
        setY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value8(Integer value) {
        setZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value9(Integer value) {
        setPosx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value10(Integer value) {
        setPosy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value11(Integer value) {
        setPosz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord value12(Long value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MissionsRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MissionsRecord
     */
    public MissionsRecord() {
        super(Missions.MISSIONS);
    }

    /**
     * Create a detached, initialised MissionsRecord
     */
    public MissionsRecord(Integer id, String name, String description, Integer time, String owner, Integer x, Integer y, Integer z, Integer posx, Integer posy, Integer posz, Long mtime) {
        super(Missions.MISSIONS);

        set(0, id);
        set(1, name);
        set(2, description);
        set(3, time);
        set(4, owner);
        set(5, x);
        set(6, y);
        set(7, z);
        set(8, posx);
        set(9, posy);
        set(10, posz);
        set(11, mtime);
    }
}
