/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.Player;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerRecord extends UpdatableRecordImpl<PlayerRecord> implements Record10<String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1879126399;

    /**
     * Setter for <code>player.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>player.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>player.pitch</code>.
     */
    public void setPitch(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>player.pitch</code>.
     */
    public BigDecimal getPitch() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>player.yaw</code>.
     */
    public void setYaw(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>player.yaw</code>.
     */
    public BigDecimal getYaw() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>player.posx</code>.
     */
    public void setPosx(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>player.posx</code>.
     */
    public BigDecimal getPosx() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>player.posy</code>.
     */
    public void setPosy(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>player.posy</code>.
     */
    public BigDecimal getPosy() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>player.posz</code>.
     */
    public void setPosz(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>player.posz</code>.
     */
    public BigDecimal getPosz() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>player.hp</code>.
     */
    public void setHp(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>player.hp</code>.
     */
    public Integer getHp() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>player.breath</code>.
     */
    public void setBreath(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>player.breath</code>.
     */
    public Integer getBreath() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>player.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>player.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>player.modification_date</code>.
     */
    public void setModificationDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>player.modification_date</code>.
     */
    public Timestamp getModificationDate() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Player.PLAYER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return Player.PLAYER.PITCH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Player.PLAYER.YAW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Player.PLAYER.POSX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Player.PLAYER.POSY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return Player.PLAYER.POSZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Player.PLAYER.HP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Player.PLAYER.BREATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Player.PLAYER.CREATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Player.PLAYER.MODIFICATION_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getPitch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getYaw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getHp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getBreath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getModificationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getPitch();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getYaw();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getHp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getBreath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getModificationDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value2(BigDecimal value) {
        setPitch(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value3(BigDecimal value) {
        setYaw(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value4(BigDecimal value) {
        setPosx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value5(BigDecimal value) {
        setPosy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value6(BigDecimal value) {
        setPosz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value7(Integer value) {
        setHp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value8(Integer value) {
        setBreath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value9(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord value10(Timestamp value) {
        setModificationDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerRecord values(String value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, Integer value7, Integer value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerRecord
     */
    public PlayerRecord() {
        super(Player.PLAYER);
    }

    /**
     * Create a detached, initialised PlayerRecord
     */
    public PlayerRecord(String name, BigDecimal pitch, BigDecimal yaw, BigDecimal posx, BigDecimal posy, BigDecimal posz, Integer hp, Integer breath, Timestamp creationDate, Timestamp modificationDate) {
        super(Player.PLAYER);

        set(0, name);
        set(1, pitch);
        set(2, yaw);
        set(3, posx);
        set(4, posy);
        set(5, posz);
        set(6, hp);
        set(7, breath);
        set(8, creationDate);
        set(9, modificationDate);
    }
}
