/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.Poi;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoiRecord extends TableRecordImpl<PoiRecord> implements Record12<Integer, String, String, String, Boolean, Integer, Integer, Integer, Integer, Integer, Integer, Long> {

    private static final long serialVersionUID = 587275238;

    /**
     * Setter for <code>poi.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>poi.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>poi.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>poi.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>poi.category</code>.
     */
    public void setCategory(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>poi.category</code>.
     */
    public String getCategory() {
        return (String) get(2);
    }

    /**
     * Setter for <code>poi.owner</code>.
     */
    public void setOwner(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>poi.owner</code>.
     */
    public String getOwner() {
        return (String) get(3);
    }

    /**
     * Setter for <code>poi.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>poi.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>poi.x</code>.
     */
    public void setX(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>poi.x</code>.
     */
    public Integer getX() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>poi.y</code>.
     */
    public void setY(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>poi.y</code>.
     */
    public Integer getY() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>poi.z</code>.
     */
    public void setZ(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>poi.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>poi.posx</code>.
     */
    public void setPosx(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>poi.posx</code>.
     */
    public Integer getPosx() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>poi.posy</code>.
     */
    public void setPosy(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>poi.posy</code>.
     */
    public Integer getPosy() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>poi.posz</code>.
     */
    public void setPosz(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>poi.posz</code>.
     */
    public Integer getPosz() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>poi.mtime</code>.
     */
    public void setMtime(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>poi.mtime</code>.
     */
    public Long getMtime() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Boolean, Integer, Integer, Integer, Integer, Integer, Integer, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, Boolean, Integer, Integer, Integer, Integer, Integer, Integer, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Poi.POI.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Poi.POI.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Poi.POI.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Poi.POI.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return Poi.POI.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Poi.POI.X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Poi.POI.Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Poi.POI.Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Poi.POI.POSX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Poi.POI.POSY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Poi.POI.POSZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Poi.POI.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value3(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value4(String value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value6(Integer value) {
        setX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value7(Integer value) {
        setY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value8(Integer value) {
        setZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value9(Integer value) {
        setPosx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value10(Integer value) {
        setPosy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value11(Integer value) {
        setPosz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord value12(Long value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoiRecord values(Integer value1, String value2, String value3, String value4, Boolean value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PoiRecord
     */
    public PoiRecord() {
        super(Poi.POI);
    }

    /**
     * Create a detached, initialised PoiRecord
     */
    public PoiRecord(Integer id, String name, String category, String owner, Boolean active, Integer x, Integer y, Integer z, Integer posx, Integer posy, Integer posz, Long mtime) {
        super(Poi.POI);

        set(0, id);
        set(1, name);
        set(2, category);
        set(3, owner);
        set(4, active);
        set(5, x);
        set(6, y);
        set(7, z);
        set(8, posx);
        set(9, posy);
        set(10, posz);
        set(11, mtime);
    }
}
