/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.Protector;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProtectorRecord extends TableRecordImpl<ProtectorRecord> implements Record9<Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> {

    private static final long serialVersionUID = 1466984584;

    /**
     * Setter for <code>protector.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>protector.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>protector.owner</code>.
     */
    public void setOwner(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>protector.owner</code>.
     */
    public String getOwner() {
        return (String) get(1);
    }

    /**
     * Setter for <code>protector.x</code>.
     */
    public void setX(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>protector.x</code>.
     */
    public Integer getX() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>protector.y</code>.
     */
    public void setY(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>protector.y</code>.
     */
    public Integer getY() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>protector.z</code>.
     */
    public void setZ(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>protector.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>protector.posx</code>.
     */
    public void setPosx(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>protector.posx</code>.
     */
    public Integer getPosx() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>protector.posy</code>.
     */
    public void setPosy(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>protector.posy</code>.
     */
    public Integer getPosy() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>protector.posz</code>.
     */
    public void setPosz(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>protector.posz</code>.
     */
    public Integer getPosz() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>protector.mtime</code>.
     */
    public void setMtime(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>protector.mtime</code>.
     */
    public Long getMtime() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Protector.PROTECTOR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Protector.PROTECTOR.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Protector.PROTECTOR.X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Protector.PROTECTOR.Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Protector.PROTECTOR.Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Protector.PROTECTOR.POSX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Protector.PROTECTOR.POSY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Protector.PROTECTOR.POSZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Protector.PROTECTOR.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value2(String value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value3(Integer value) {
        setX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value4(Integer value) {
        setY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value5(Integer value) {
        setZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value6(Integer value) {
        setPosx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value7(Integer value) {
        setPosy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value8(Integer value) {
        setPosz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord value9(Long value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtectorRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProtectorRecord
     */
    public ProtectorRecord() {
        super(Protector.PROTECTOR);
    }

    /**
     * Create a detached, initialised ProtectorRecord
     */
    public ProtectorRecord(Integer id, String owner, Integer x, Integer y, Integer z, Integer posx, Integer posy, Integer posz, Long mtime) {
        super(Protector.PROTECTOR);

        set(0, id);
        set(1, owner);
        set(2, x);
        set(3, y);
        set(4, z);
        set(5, posx);
        set(6, posy);
        set(7, posz);
        set(8, mtime);
    }
}
