/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.TileserverBlockChanges;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TileserverBlockChangesRecord extends UpdatableRecordImpl<TileserverBlockChangesRecord> implements Record4<Integer, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1868329322;

    /**
     * Setter for <code>tileserver_block_changes.posx</code>.
     */
    public void setPosx(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tileserver_block_changes.posx</code>.
     */
    public Integer getPosx() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tileserver_block_changes.posy</code>.
     */
    public void setPosy(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tileserver_block_changes.posy</code>.
     */
    public Integer getPosy() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tileserver_block_changes.posz</code>.
     */
    public void setPosz(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>tileserver_block_changes.posz</code>.
     */
    public Integer getPosz() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>tileserver_block_changes.changed</code>.
     */
    public void setChanged(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>tileserver_block_changes.changed</code>.
     */
    public Boolean getChanged() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TileserverBlockChanges.TILESERVER_BLOCK_CHANGES.POSX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TileserverBlockChanges.TILESERVER_BLOCK_CHANGES.POSY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TileserverBlockChanges.TILESERVER_BLOCK_CHANGES.POSZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return TileserverBlockChanges.TILESERVER_BLOCK_CHANGES.CHANGED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getChanged();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getChanged();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TileserverBlockChangesRecord value1(Integer value) {
        setPosx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TileserverBlockChangesRecord value2(Integer value) {
        setPosy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TileserverBlockChangesRecord value3(Integer value) {
        setPosz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TileserverBlockChangesRecord value4(Boolean value) {
        setChanged(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TileserverBlockChangesRecord values(Integer value1, Integer value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TileserverBlockChangesRecord
     */
    public TileserverBlockChangesRecord() {
        super(TileserverBlockChanges.TILESERVER_BLOCK_CHANGES);
    }

    /**
     * Create a detached, initialised TileserverBlockChangesRecord
     */
    public TileserverBlockChangesRecord(Integer posx, Integer posy, Integer posz, Boolean changed) {
        super(TileserverBlockChanges.TILESERVER_BLOCK_CHANGES);

        set(0, posx);
        set(1, posy);
        set(2, posz);
        set(3, changed);
    }
}
