/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.Trainline;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrainlineRecord extends TableRecordImpl<TrainlineRecord> implements Record12<Integer, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> {

    private static final long serialVersionUID = -2047160822;

    /**
     * Setter for <code>trainline.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>trainline.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trainline.station</code>.
     */
    public void setStation(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>trainline.station</code>.
     */
    public String getStation() {
        return (String) get(1);
    }

    /**
     * Setter for <code>trainline.line</code>.
     */
    public void setLine(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>trainline.line</code>.
     */
    public String getLine() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trainline.index</code>.
     */
    public void setIndex(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>trainline.index</code>.
     */
    public Integer getIndex() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>trainline.owner</code>.
     */
    public void setOwner(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>trainline.owner</code>.
     */
    public String getOwner() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trainline.x</code>.
     */
    public void setX(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>trainline.x</code>.
     */
    public Integer getX() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>trainline.y</code>.
     */
    public void setY(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>trainline.y</code>.
     */
    public Integer getY() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>trainline.z</code>.
     */
    public void setZ(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>trainline.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>trainline.posx</code>.
     */
    public void setPosx(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>trainline.posx</code>.
     */
    public Integer getPosx() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>trainline.posy</code>.
     */
    public void setPosy(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>trainline.posy</code>.
     */
    public Integer getPosy() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>trainline.posz</code>.
     */
    public void setPosz(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>trainline.posz</code>.
     */
    public Integer getPosz() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>trainline.mtime</code>.
     */
    public void setMtime(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>trainline.mtime</code>.
     */
    public Long getMtime() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Trainline.TRAINLINE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Trainline.TRAINLINE.STATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Trainline.TRAINLINE.LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Trainline.TRAINLINE.INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Trainline.TRAINLINE.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Trainline.TRAINLINE.X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Trainline.TRAINLINE.Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Trainline.TRAINLINE.Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Trainline.TRAINLINE.POSX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Trainline.TRAINLINE.POSY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Trainline.TRAINLINE.POSZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Trainline.TRAINLINE.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value2(String value) {
        setStation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value3(String value) {
        setLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value4(Integer value) {
        setIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value5(String value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value6(Integer value) {
        setX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value7(Integer value) {
        setY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value8(Integer value) {
        setZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value9(Integer value) {
        setPosx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value10(Integer value) {
        setPosy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value11(Integer value) {
        setPosz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord value12(Long value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TrainlineRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Integer value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrainlineRecord
     */
    public TrainlineRecord() {
        super(Trainline.TRAINLINE);
    }

    /**
     * Create a detached, initialised TrainlineRecord
     */
    public TrainlineRecord(Integer id, String station, String line, Integer index, String owner, Integer x, Integer y, Integer z, Integer posx, Integer posy, Integer posz, Long mtime) {
        super(Trainline.TRAINLINE);

        set(0, id);
        set(1, station);
        set(2, line);
        set(3, index);
        set(4, owner);
        set(5, x);
        set(6, y);
        set(7, z);
        set(8, posx);
        set(9, posy);
        set(10, posz);
        set(11, mtime);
    }
}
