/*
 * This file is generated by jOOQ.
*/
package io.rudin.minetest.tileserver.blockdb.tables.records;


import io.rudin.minetest.tileserver.blockdb.tables.Travelnet;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TravelnetRecord extends TableRecordImpl<TravelnetRecord> implements Record11<Integer, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> {

    private static final long serialVersionUID = -1045922744;

    /**
     * Setter for <code>travelnet.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>travelnet.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>travelnet.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>travelnet.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>travelnet.network</code>.
     */
    public void setNetwork(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>travelnet.network</code>.
     */
    public String getNetwork() {
        return (String) get(2);
    }

    /**
     * Setter for <code>travelnet.owner</code>.
     */
    public void setOwner(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>travelnet.owner</code>.
     */
    public String getOwner() {
        return (String) get(3);
    }

    /**
     * Setter for <code>travelnet.x</code>.
     */
    public void setX(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>travelnet.x</code>.
     */
    public Integer getX() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>travelnet.y</code>.
     */
    public void setY(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>travelnet.y</code>.
     */
    public Integer getY() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>travelnet.z</code>.
     */
    public void setZ(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>travelnet.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>travelnet.posx</code>.
     */
    public void setPosx(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>travelnet.posx</code>.
     */
    public Integer getPosx() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>travelnet.posy</code>.
     */
    public void setPosy(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>travelnet.posy</code>.
     */
    public Integer getPosy() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>travelnet.posz</code>.
     */
    public void setPosz(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>travelnet.posz</code>.
     */
    public Integer getPosz() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>travelnet.mtime</code>.
     */
    public void setMtime(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>travelnet.mtime</code>.
     */
    public Long getMtime() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Travelnet.TRAVELNET.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Travelnet.TRAVELNET.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Travelnet.TRAVELNET.NETWORK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Travelnet.TRAVELNET.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Travelnet.TRAVELNET.X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Travelnet.TRAVELNET.Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Travelnet.TRAVELNET.Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Travelnet.TRAVELNET.POSX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Travelnet.TRAVELNET.POSY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Travelnet.TRAVELNET.POSZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Travelnet.TRAVELNET.MTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNetwork();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNetwork();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPosx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPosy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPosz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getMtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value3(String value) {
        setNetwork(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value4(String value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value5(Integer value) {
        setX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value6(Integer value) {
        setY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value7(Integer value) {
        setZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value8(Integer value) {
        setPosx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value9(Integer value) {
        setPosy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value10(Integer value) {
        setPosz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord value11(Long value) {
        setMtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TravelnetRecord values(Integer value1, String value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, Integer value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TravelnetRecord
     */
    public TravelnetRecord() {
        super(Travelnet.TRAVELNET);
    }

    /**
     * Create a detached, initialised TravelnetRecord
     */
    public TravelnetRecord(Integer id, String name, String network, String owner, Integer x, Integer y, Integer z, Integer posx, Integer posy, Integer posz, Long mtime) {
        super(Travelnet.TRAVELNET);

        set(0, id);
        set(1, name);
        set(2, network);
        set(3, owner);
        set(4, x);
        set(5, y);
        set(6, z);
        set(7, posx);
        set(8, posy);
        set(9, posz);
        set(10, mtime);
    }
}
